[package]
name = "guid"
version = "0.1.0"
authors = ["sanfusu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]
guid_proc = { version = "0.1", path = "./proc" }

[workspace]
members=['./proc']